/**Class for creating gods and cleaning up the main application class*/

package exercise_7;


import javafx.collections.ObservableList;

public class NorseGodCreater {

    /** Constructor */
    public NorseGodCreater () {

    }

    /** Method for creating the Godlist
     * @param godlist ObservableList<NorseGod>
     * @return  godlist ObservableList<NorseGod>
     */
    public ObservableList<NorseGod> creator(ObservableList<NorseGod> godlist){
        godlist.add(new NorseGod("Odin", "Aesir", "Odin (/ˈoʊdɪn/;[1] from Old Norse: Óðinn, IPA: [ˈoːðinː]) is a widely revered god in Germanic mythology. Norse mythology, the source of most surviving information about him, associates Odin with wisdom, healing, death, royalty, the gallows, knowledge, war, battle, victory, sorcery, poetry, frenzy, and the runic alphabet, and project him as the husband of the goddess Frigg. In wider Germanic mythology and paganism, the god was known in Old English and Old Saxon as Wōden, in Old Dutch as Wuodan,[2] and in Old High German as Wuotan.\n" +
                "\n" +
                "Odin appears as a prominent god throughout the recorded history of Northern Europe, from the Roman occupation of regions of Germania (from c.  2 BCE) through the tribal expansions of the Migration Period (4th to 6th centuries CE) and the Viking Age (8th to 11th centuries CE). In the modern period the rural folklore of Germanic Europe continued to acknowledge Odin. References to him appear in place names throughout regions historically inhabited by the ancient Germanic peoples, and the day of the week Wednesday bears his name in many Germanic languages, including in English.\n" +
                "\n" +
                "In Old English texts, Odin holds a particular place as a euhemerized ancestral figure among royalty, and he is frequently referred to as a founding figure among various other Germanic peoples, such as the Langobards. Forms of his name appear frequently throughout the Germanic record, though narratives regarding Odin are mainly found in Old Norse works recorded in Iceland, primarily around the 13th century. These texts make up the bulk of modern understanding of Norse mythology.\n" +
                "\n" +
                "Old Norse texts portray Odin as one-eyed and long-bearded, frequently wielding a spear named Gungnir and wearing a cloak and a broad hat. He is often accompanied by his animal companions and familiars—the wolves Geri and Freki and the ravens Huginn and Muninn, who bring him information from all over Midgard—and rides the flying, eight-legged steed Sleipnir across the sky and into the underworld. Odin is the son of Bestla and Borr and has two brothers, Vili and Vé. Odin is attested as having many sons, most famously the gods Thor (with Jörð) and Baldr (with Frigg), and is known by hundreds of names. In these texts he frequently seeks greater knowledge, at times in disguise (most famously by obtaining the Mead of Poetry), makes wagers with his wife Frigg over the outcome of exploits, and takes part both in the creation of the world by way of slaying the primordial being Ymir and in giving the gift of life to the first two humans Ask and Embla. Odin has a particular association with Yule, and mankind's knowledge of both the runes and poetry is also attributed to him, giving Odin aspects of the culture hero.\n" +
                "\n" +
                "Old Norse texts associate female beings connected with the battlefield—the valkyries—with the god, and Odin oversees Valhalla, where he receives half of those who die in battle, the einherjar. The other half are chosen by the goddess Freyja for her afterlife-location, Fólkvangr. Odin consults the disembodied, herb-embalmed head of the wise being Mímir for advice, and during the foretold events of Ragnarök Odin is told to lead the einherjar into battle before being consumed by the monstrous wolf Fenrir. In later folklore Odin appears as a leader of the Wild Hunt, a ghostly procession of the dead through the winter sky. He is associated with charms and other forms of magic, particularly in Old English and Old Norse texts.\n" +
                "\n" +
                "Odin is a frequent subject of interest in Germanic studies, and scholars have advanced numerous theories regarding his development. Some of these focus on Odin's particular relation to other figures; for example, the fact that Freyja's husband Óðr appears to be something of an etymological doublet of the god, whereas Odin's wife Frigg is in many ways similar to Freyja, and that Odin has a particular relation to the figure of Loki. Other approaches focus on Odin's place in the historical record, a frequent question being whether the figure of Odin derives from Proto-Indo-European mythology, or whether he developed later in Germanic society. In the modern period the figure of Odin has inspired numerous works of poetry, music, and other cultural expressions. He is venerated in most forms of the new religious movement Heathenry, together with other gods venerated by the ancient Germanic peoples; some branches focus particularly on him."));

        godlist.add(new NorseGod("Frigg", "Aesir", "Frigg (/frɪɡ/)[1] is a goddess in Germanic mythology. In Norse mythology, the source of most surviving information about her, she is associated with foresight and wisdom, and dwells in the wetland halls of Fensalir. In wider Germanic mythology, she is known in Old High German as Frīja, in Langobardic as Frea, in Old English as Frīg, and in Old Saxon as Frī. Nearly all sources portray her as the wife of the god Odin.\n" +
                "\n" +
                "In Old High German and Old Norse sources, she is specifically connected with Fulla, but she is also associated with the goddesses Lofn, Hlín, Gná, and ambiguously with the Earth, otherwise personified as an apparently separate entity Jörð (Old Norse \"Earth\"). The children of Frigg and Odin include the gleaming god Baldr. Due to significant thematic overlap, scholars have proposed a connection to the goddess Freyja.\n" +
                "\n" +
                "The English weekday name Friday (ultimately meaning 'Frigg's Day') bears her name. After Christianization, the mention of Frigg continued to occur in Scandinavian folklore. During modern times, Frigg has appeared in popular culture, has been the subject of art and receives veneration in Germanic Neopaganism."));

        godlist.add(new NorseGod("Thor", "Aesir", "In Germanic mythology, Thor (/θɔːr/; from Old Norse: Þórr, runic ᚦᚢᚱ þur) is a hammer-wielding god associated with lightning, thunder, storms, sacred groves and trees, strength, the protection of mankind and also hallowing and fertility. Besides Old Norse Þórr, extensions of the god occur in Old English as Þunor and in Old High German as Donar (runic ᚦᛟᚾᚨᚱ þonar). All forms of the deity stem from a Common Germanic *Þunraz (meaning thunder).\n" +
                "\n" +
                "Thor is a prominently mentioned god throughout the recorded history of the Germanic peoples, from the Roman occupation of regions of Germania, to the Germanic expansions of the Migration Period, to his high popularity during the Viking Age, when, in the face of the process of the Christianization of Scandinavia, emblems of his hammer, Mjölnir, were worn and Norse pagan personal names containing the name of the god bear witness to his popularity.\n" +
                "\n" +
                "Due to the nature of the Germanic corpus, narratives featuring Thor are only attested in Old Norse, where Thor appears throughout Norse mythology. Norse mythology, largely recorded in Iceland from traditional material stemming from Scandinavia, provides numerous tales featuring the god. In these sources, Thor bears at least fifteen names, is the husband of the golden-haired goddess Sif, is the lover of the jötunn Járnsaxa, and is generally described as fierce eyed, red haired and red bearded.[1] With Sif, Thor fathered the goddess (and possible valkyrie) Þrúðr; with Járnsaxa, he fathered Magni; with a mother whose name is not recorded, he fathered Móði, and he is the stepfather of the god Ullr. By way of Odin, Thor has numerous brothers, including Baldr. Thor has two servants, Þjálfi and Röskva, rides in a cart or chariot pulled by two goats, Tanngrisnir and Tanngnjóstr (that he eats and resurrects), and is ascribed three dwellings (Bilskirnir, Þrúðheimr, and Þrúðvangr). Thor wields the mountain-crushing hammer, Mjölnir, wears the belt Megingjörð and the iron gloves Járngreipr, and owns the staff Gríðarvölr. Thor's exploits, including his relentless slaughter of his foes and fierce battles with the monstrous serpent Jörmungandr—and their foretold mutual deaths during the events of Ragnarök—are recorded throughout sources for Norse mythology.\n" +
                "\n" +
                "Into the modern period, Thor continued to be acknowledged in rural folklore throughout Germanic-speaking Europe. Thor is frequently referred to in place names, the day of the week Thursday bears his name (modern English Thursday derives from Old English Þūnresdæg, 'Þunor's day'), and names stemming from the pagan period containing his own continue to be used today, particularly in Scandinavia. Thor has inspired numerous works of art and references to Thor appear in modern popular culture. Like other Germanic deities, veneration of Thor is revived in the modern period in Heathenry."));

        godlist.add(new NorseGod("Baldr", "Aesir", "Baldr (also Balder, Baldur) is a god in Norse mythology and a son of the god Odin and the goddess Frigg. He has numerous brothers, such as Thor and Váli.\n" +
                "\n" +
                "During the 12th century, Danish accounts by Saxo Grammaticus and other Danish Latin chroniclers recorded a euhemerized account of his story. Compiled in Iceland during the 13th century, but based on much older Old Norse poetry, the Poetic Edda and the Prose Edda contain numerous references to the death of Baldr as both a great tragedy to the Æsir and a harbinger of Ragnarök.\n" +
                "\n" +
                "According to Gylfaginning, a book of Snorri Sturluson's Prose Edda, Baldr's wife is Nanna and their son is Forseti. Baldr had the greatest ship ever built, Hringhorni, and there is no place more beautiful than his hall, Breidablik."));

        godlist.add(new NorseGod("Loki", "Giant", "Loki (Old Norse: [ˈloki], Modern Icelandic: [ˈlɔːkɪ], often Anglicized as /ˈloʊki/) is a god in Norse mythology. Loki is in some sources the son of Fárbauti and Laufey, and the brother of Helblindi and Býleistr. By the jötunn Angrboða, Loki is the father of Hel, the wolf Fenrir, and the world serpent Jörmungandr. By his wife Sigyn, Loki is the father of Narfi and/or Nari. By the stallion Svaðilfari, Loki is the mother—giving birth in the form of a mare—to the eight-legged horse Sleipnir. In addition, Loki is referred to as the father of Váli in Prose Edda, though this source also refers to Odin as the father of Váli twice, and Váli is found mentioned as a son of Loki only once.\n" +
                "\n" +
                "Loki's relation with the gods varies by source; Loki sometimes assists the gods and sometimes behaves maliciously towards them. Loki is a shape shifter and in separate incidents appears in the form of a salmon, a mare, a fly, and possibly an elderly woman named Þökk (Old Norse 'thanks'). Loki's positive relations with the gods end with his role in engineering the death of the god Baldr, and eventually, Váli binds Loki with the entrails of one of his sons. In both the Poetic Edda and the Prose Edda, the goddess Skaði is responsible for placing a serpent above him while he is bound. The serpent drips venom from above him that Sigyn collects into a bowl; however, she must empty the bowl when it is full, and the venom that drips in the meantime causes Loki to writhe in pain, thereby causing earthquakes. With the onset of Ragnarök, Loki is foretold to slip free from his bonds and to fight against the gods among the forces of the jötnar, at which time he will encounter the god Heimdallr, and the two will slay each other.\n" +
                "\n" +
                "Loki is referred to in the Poetic Edda, compiled in the 13th century from earlier traditional sources; the Prose Edda and Heimskringla, written in the 13th century by Snorri Sturluson; the Norwegian Rune Poems, in the poetry of skalds, and in Scandinavian folklore. Loki may be depicted on the Snaptun Stone, the Kirkby Stephen Stone, and the Gosforth Cross. Scholars have debated Loki's origins and role in Norse mythology, which some have described as that of a trickster god. Loki has been depicted in or is referenced in a variety of media in modern popular culture."));

        godlist.add(new NorseGod("Ymir", "Giant", "In Norse mythology, Ymir (/ˈiːmɪər/),[1] Aurgelmir, Brimir, or Bláinn is the ancestor of all jötnar. Ymir is attested in the Poetic Edda, compiled in the 13th century from earlier traditional material, in the Prose Edda, written by Snorri Sturluson in the 13th century, and in the poetry of skalds. Taken together, several stanzas from four poems collected in the Poetic Edda refer to Ymir as a primeval being who was born from venom that dripped from the icy rivers Élivágar and lived in the grassless void of Ginnungagap. Ymir birthed a male and female from the pits of his arms, and his legs together begat a six-headed being. The gods Odin, Vili and Vé fashioned the Earth (elsewhere personified as a goddess; Jörð) from his flesh, from his blood the ocean, from his bones the mountains, from his hair the trees, from his brains the clouds, from his skull the heavens, and from his eyebrows the middle realm in which mankind lives, Midgard. In addition, one stanza relates that the dwarves were given life by the gods from Ymir's flesh and blood (or the Earth and sea).\n" +
                "\n" +
                "In the Prose Edda, a narrative is provided that draws from, adds to, and differs from the accounts in the Poetic Edda. According to the Prose Edda, after Ymir was formed from the elemental drops, so too was Auðumbla, a primeval cow, whose milk Ymir fed from. The Prose Edda also states that three gods killed Ymir; the brothers Odin, Vili and Vé, and details that, upon Ymir's death, his blood caused an immense flood. Scholars have debated as to what extent Snorri's account of Ymir is an attempt to synthesize a coherent narrative for the purpose of the Prose Edda and to what extent Snorri drew from traditional material outside of the corpus that he cites. By way of historical linguistics and comparative mythology, scholars have linked Ymir to Tuisto, the Proto-Germanic being attested by Tacitus in his 1st century AD work Germania and have identified Ymir as an echo of a primordial being reconstructed in Proto-Indo-European mythology."));

        godlist.add(new NorseGod("Mimir", "Giant", "Mímir or Mim is a figure in Norse mythology, renowned for his knowledge and wisdom, who is beheaded during the Æsir-Vanir War. Afterward, the god Odin carries around Mímir's head and it recites secret knowledge and counsel to him.\n" +
                "\n" +
                "Mímir is attested in the Poetic Edda, compiled in the 13th century from earlier traditional sources, the Prose Edda, written in the 13th century by Snorri Sturluson of Iceland, and in euhemerized form as one of the Æsir in Heimskringla, also written by Snorri Sturluson in the 13th century. Mímir's name appears in the names of the well Mímisbrunnr, and the names Mímameiðr and Hoddmímis holt, which scholars generally consider to be names for Yggdrasil. Scholars have proposed that Bestla may be Mímir's sister, and therefore Mímir would be Odin's uncle."));

        godlist.add(new NorseGod("Heimdallr", "Aesir", "In Norse mythology, Heimdallr is a god who possesses the resounding horn Gjallarhorn, owns the golden-maned horse Gulltoppr, is called the shining god and the whitest of the gods, has gold teeth, and is the son of Nine Mothers (who may represent personified waves). Heimdallr is attested as possessing foreknowledge, keen eyesight and hearing, and keeps watch for invaders and the onset of Ragnarök while drinking fine mead in his dwelling Himinbjörg, located where the burning rainbow bridge Bifröst meets the sky. Heimdallr is said to be the originator of social classes among humanity and once regained Freyja's treasured possession Brísingamen while doing battle in the shape of a seal with Loki. Heimdallr and Loki are foretold to kill one another during the events of Ragnarök. Heimdallr is additionally referred to as Rig, Hallinskiði, Gullintanni, and Vindlér or Vindhlér.\n" +
                "\n" +
                "Heimdallr is attested in the Poetic Edda, compiled in the 13th century from earlier traditional material; in the Prose Edda and Heimskringla, both written in the 13th century by Snorri Sturluson; in the poetry of skalds; and on an Old Norse runic inscription found in England. Two lines of an otherwise lost poem about the god, Heimdalargaldr, survive. Due to the problematic and enigmatic nature of these attestations, scholars have produced various theories about the nature of the god, including his apparent relation to rams, that he may be a personification of or connected to the world tree Yggdrasil, and potential Indo-European cognates."));

        return godlist;
    }
}
